groups:
  - name: logging.alerts
    rules:
      # Promtail Instance Down
      - alert: PromtailInstanceDown
        expr: up{job="promtail"} == 0
        for: 2m
        labels:
          severity: critical
          component: promtail
        annotations:
          summary: "Promtail instance is down"
          description: "Promtail instance {{ $labels.instance }} has been down for more than 2 minutes. Log collection is affected."

      # High Log Processing Errors
      - alert: PromtailHighEncodingFailures
        expr: rate(promtail_encoding_failures_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          component: promtail
        annotations:
          summary: "High encoding failures in Promtail"
          description: "Promtail instance {{ $labels.instance }} is experiencing {{ $value }} encoding failures per second for the last 5 minutes."

      # High Request Errors to Loki
      - alert: PromtailHighRequestErrors
        expr: rate(promtail_request_errors_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          component: promtail
        annotations:
          summary: "High request errors in Promtail"
          description: "Promtail instance {{ $labels.instance }} is experiencing {{ $value }} request errors per second when sending logs to Loki."

      # High Memory Usage
      - alert: PromtailHighMemoryUsage
        expr: process_resident_memory_bytes{job="promtail"} > 500 * 1024 * 1024
        for: 10m
        labels:
          severity: warning
          component: promtail
        annotations:
          summary: "Promtail high memory usage"
          description: "Promtail instance {{ $labels.instance }} is using {{ $value | humanize1024 }} of memory, exceeding 500MB threshold."

      # No Log Activity Detected
      - alert: PromtailNoLogActivity
        expr: rate(promtail_read_lines_total[10m]) == 0
        for: 15m
        labels:
          severity: warning
          component: promtail
        annotations:
          summary: "No log activity detected in Promtail"
          description: "Promtail instance {{ $labels.instance }} has not read any log lines for {{ $labels.path }} in the last 15 minutes."

      # File Not Being Processed
      - alert: PromtailFileNotActive
        expr: promtail_files_active_total{job="promtail"} == 0
        for: 10m
        labels:
          severity: warning
          component: promtail
        annotations:
          summary: "No active files being monitored by Promtail"
          description: "Promtail instance {{ $labels.instance }} has no active files being monitored for path {{ $labels.path }}."

      # High CPU Usage
      - alert: PromtailHighCPUUsage
        expr: rate(process_cpu_seconds_total{job="promtail"}[5m]) * 100 > 80
        for: 10m
        labels:
          severity: warning
          component: promtail
        annotations:
          summary: "Promtail high CPU usage"
          description: "Promtail instance {{ $labels.instance }} is using {{ $value }}% CPU for the last 10 minutes."

  - name: loki.alerts
    rules:
      # Loki Instance Down (inferred from lack of log ingestion)
      - alert: LokiNoIngestion
        expr: absent_over_time(up{job="promtail"}[5m]) or (rate(promtail_sent_entries_total[5m]) == 0 and up{job="promtail"} == 1)
        for: 5m
        labels:
          severity: critical
          component: loki
        annotations:
          summary: "Loki appears to not be receiving logs"
          description: "No logs are being sent to Loki despite Promtail being up, suggesting Loki may be down or unreachable."

